import pyfiglet
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.layout import Layout
from rich.text import Text
import psutil
import platform
from datetime import datetime
# Initialize console
console = Console()
layout = Layout()
# Layout structure
layout.split(
    Layout(name="header", size=3),
    Layout(name="body", ratio=2),
    Layout(name="footer", size=3),
)
layout["body"].split_row(
    Layout(name="left"),
    Layout(name="right"),
)
# ---------- HEADER ----------
ascii_banner = pyfiglet.figlet_format("CLI Dashboard", font="slant")
layout["header"].update(Panel(Text(ascii_banner, justify="center"), style="bold cyan"))
# ---------- LEFT: SYSTEM STATS ----------
def get_system_stats():
    uname = platform.uname()
    boot_time = datetime.fromtimestamp(psutil.boot_time()).strftime("%Y-%m-%d %H:%M:%S")
    stats = Table(title="💻 System Information", title_style="bold magenta")
    stats.add_column("Property", style="cyan", no_wrap=True)
    stats.add_column("Value", style="green")
    stats.add_row("System", uname.system)
    stats.add_row("Node Name", uname.node)
    stats.add_row("Release", uname.release)
    stats.add_row("Version", uname.version)
    stats.add_row("Machine", uname.machine)
    stats.add_row("Processor", uname.processor)
    stats.add_row("Boot Time", boot_time)
    return stats
layout["left"].update(get_system_stats())
# ---------- RIGHT: TASK TABLE ----------
task_table = Table(title="📋 Tasks", title_style="bold magenta")
task_table.add_column("Task", style="cyan", no_wrap=True)
task_table.add_column("Status", style="green")
task_table.add_column("Progress", justify="right", style="yellow")
task_table.add_row("Data Sync", "✅ Complete", "100%")
task_table.add_row("Model Training", "⚙️ Running", "76%")
task_table.add_row("Report Generation", "⏳ Pending", "0%")
layout["right"].update(task_table)
# ---------- FOOTER ----------
footer_panel = Panel("[bold cyan]All systems operational. 🚀\nGenerated by your Python CLI dashboard.[/bold cyan]",
                     title="Status", border_style="blue")
layout["footer"].update(footer_panel)

# ---------- DISPLAY ----------
console.clear()
console.print(layout)
